# NumPy

Numeric Python

n-D

# Creating a Vector

In [1]:
!pip install numpy

In [2]:
import numpy as np

v = np.array([1,2,3])

print(v)

[1 2 3]


In [3]:
print(type(v))

<class 'numpy.ndarray'>


In [4]:
v = np.array([[1],[2],[3]])

print(v)

[[1]
 [2]
 [3]]


In [ ]:
0th dimension ->       .
1th dimension ->       .________. #number line
2nd D         ->       ._____|____.
3rd D         ->       .____|____.
                           /
4th D

# Creating a Matrix

In [5]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(matrix[0][0])

1


# Selecting Elements

In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matrix[2:5]

array([[7, 8, 9]])

In [10]:
matrix[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [11]:
matrix[0,0]

1

In [12]:
matrix[1,1]

5

In [ ]:
00  01  02
10  11  12
20  21  22

In [13]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matrix[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [15]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

# Describing a Matrix

In [16]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
matrix.shape

(3, 3)

In [18]:
matrix.ndim

2

In [19]:
type(matrix.ndim)

int

In [20]:
matrix.size

9

# Finding max and min values

In [21]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(np.max(matrix))

9


In [23]:
print(np.min(matrix))

1


In [24]:
print(np.max(matrix, axis=0))  # columns

[7 8 9]


In [25]:
print(np.max(matrix, axis=1))  # rows

[3 6 9]


In [27]:
# help(np.max)

# Mean, Variance and Standard Deviation

In [49]:
matrix = np.array([[1,2,1],[1,1,1],[1,1,100]])

print(matrix)

[[  1   2   1]
 [  1   1   1]
 [  1   1 100]]


In [44]:
print(np.mean(matrix))  # 45/9 = 5.0

1.1111111111111112


In [45]:
print(np.median(matrix))

1.0


In [46]:
print(np.std(matrix))

0.3142696805273545


In [47]:
print(np.var(matrix))

0.09876543209876544


In [50]:
np.max(matrix) - np.min(matrix)

99

In [ ]:
# IQR

# Reshaping Arrays

In [51]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [53]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [54]:
print(matrix.reshape(4,2))

ValueError: cannot reshape array of size 9 into shape (4,2)

In [55]:
print(matrix.reshape(1,9))

[[1 2 3 4 5 6 7 8 9]]


In [56]:
print(matrix.reshape(9))   # 1-d array

[1 2 3 4 5 6 7 8 9]


In [57]:
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


# Transpose of Matrix

In [58]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Determinanat and Rank

In [60]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
print(np.linalg.det(matrix))

-9.51619735392994e-16


In [62]:
print(np.linalg.matrix_rank(matrix))

2


# Diagonal

In [63]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
print(matrix.diagonal())

[1 5 9]


In [65]:
print(matrix.diagonal(offset = 1))

[2 6]


In [66]:
print(matrix.diagonal(offset = 2))

[3]


In [67]:
print(matrix.diagonal(offset = -1))

[4 8]


# Dot Product

In [68]:
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix1)
print(matrix2)

print(np.dot(matrix1,matrix2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [69]:
matrix1 * matrix2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [71]:
matrix1 @ matrix2    # dot product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# Random Values

In [82]:
np.random.seed(10)

print(np.random.randint(0,11,3))

[9 4 0]


In [85]:
print(np.random.normal(1.0,2.0,3))  # normal distribution of data
#                    mean, std, number of data points

[-0.3642477   0.07756334  2.93133228]
